### ISSUE TITLE
Rename NuGet Package

### ISSUE THREAD

**Issue by jamesmontemagno** [sbondini/Xamarin.Badge#1]
Hey there! 
Very cool plugin. Was wondering if you could change the actual package name that is on NuGet itself. 

Usually I recommend: Company.Plugin.Feature or Developer.Plugin.Feature.

Ideally "Xamarin." would be reserved for nugets coming from us directly.  I personally use "Xam.Plugin.Feature" for mine, but none of them start with Xamarin directly.

Thanks!

**Comment by sbondini** [comment]
Renamed to Xam.Plugin.Badge
https://www.nuget.org/packages/Xam.Plugin.Badge/
